[features]
seeds = false
skip-lint = false

[programs.localnet]
agbero = "Agbero1111111111111111111111111111111111111"

[programs.devnet]
agbero = "Agbero1111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "node scripts/initialize.js"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
